/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datos;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        // this.setLocationRelativeTo(this);//centra la ventana
        this.setLocation(300, 350);
        this.setResizable(false);// para modificar el tamaño 
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        //Asignar imagenes a cada label (todos los label de imagenes estaran ocultos al cargar la ventana)
        ImageIcon imgNieve = new ImageIcon(getClass().getResource("/Conversor/nieve.jpg"));
        Icon icNieve = new ImageIcon(imgNieve.getImage().getScaledInstance(lbNieve.getWidth(), lbNieve.getHeight(), Image.SCALE_DEFAULT));
        lbNieve.setIcon(icNieve);

        ImageIcon imgFrio = new ImageIcon(getClass().getResource("/Conversor/frio.jpg"));
        Icon icFrio = new ImageIcon(imgFrio.getImage().getScaledInstance(lbFrio.getWidth(), lbFrio.getHeight(), Image.SCALE_DEFAULT));
        lbFrio.setIcon(icFrio);

        ImageIcon imgTemplado = new ImageIcon(getClass().getResource("/Conversor/templado.jpg"));
        Icon icTemplado = new ImageIcon(imgTemplado.getImage().getScaledInstance(lbTemplado.getWidth(), lbTemplado.getHeight(), Image.SCALE_DEFAULT));
        lbTemplado.setIcon(icTemplado);

        ImageIcon imgCalido = new ImageIcon(getClass().getResource("/Conversor/calido.jpg"));
        Icon icCalido = new ImageIcon(imgCalido.getImage().getScaledInstance(lbCalido.getWidth(), lbCalido.getHeight(), Image.SCALE_DEFAULT));
        lbCalido.setIcon(icCalido);

        ImageIcon imgCaluroso = new ImageIcon(getClass().getResource("/Conversor/caluroso.jpg"));
        Icon icCaluroso = new ImageIcon(imgCaluroso.getImage().getScaledInstance(lbCaluroso.getWidth(), lbCaluroso.getHeight(), Image.SCALE_DEFAULT));
        lbCaluroso.setIcon(icCaluroso);

        //Ocultar los label de imagenes al cargar la ventana
        lbNieve.setVisible(false);
        lbFrio.setVisible(false);
        lbTemplado.setVisible(false);
        lbCalido.setVisible(false);
        lbCaluroso.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the
     * form.ibImagen.setIcon(new ImageIcon(getClass().getResource("/imagenes
     * frutas/fresa.jpeg"))); ibImagen.setIcon(new
     * ImageIcon(getClass().getResource("/imagenes frutas/naranja.jpeg")));
     * ibImagen.setIcon(new ImageIcon(getClass().getResource("/imagenes
     * frutas/manzana.jpeg"))); ibImagen.setIcon(new
     * ImageIcon(getClass().getResource("/imagenes frutas/durazno.jpeg")));
     * ibImagen.setIcon(new ImageIcon(getClass().getResource("/imagenes
     * frutas/pera.jpeg"))); ibImagen.setIcon(new
     * ImageIcon(getClass().getResource("/imagenes frutas/platano.jpeg")));
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        slValores = new javax.swing.JSlider();
        lbCentigrados = new javax.swing.JLabel();
        lbFahrenheit = new javax.swing.JLabel();
        lbc = new javax.swing.JLabel();
        lbf = new javax.swing.JLabel();
        lbCaluroso = new javax.swing.JLabel();
        lbNieve = new javax.swing.JLabel();
        lbFrio = new javax.swing.JLabel();
        lbTemplado = new javax.swing.JLabel();
        lbCalido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversión de Grados");

        pnPrincipal.setBackground(new java.awt.Color(204, 255, 204));
        pnPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbTitulo.setText("Conversión de Grados");
        pnPrincipal.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 510, 70));

        slValores.setBackground(new java.awt.Color(204, 255, 204));
        slValores.setMaximum(200);
        slValores.setMinimum(-50);
        slValores.setValue(75);
        slValores.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slValoresStateChanged(evt);
            }
        });
        pnPrincipal.add(slValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 550, -1));

        lbCentigrados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCentigrados.setText("0");
        pnPrincipal.add(lbCentigrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 110, -1));

        lbFahrenheit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFahrenheit.setText("0");
        pnPrincipal.add(lbFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 110, -1));

        lbc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbc.setText("Centigrados");
        pnPrincipal.add(lbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 160, -1));

        lbf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbf.setText("Fahrenheit");
        pnPrincipal.add(lbf, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 160, -1));
        pnPrincipal.add(lbCaluroso, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 120, 100));
        pnPrincipal.add(lbNieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 120, 100));
        pnPrincipal.add(lbFrio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 120, 100));
        pnPrincipal.add(lbTemplado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 120, 100));
        pnPrincipal.add(lbCalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 120, 100));

        getContentPane().add(pnPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slValoresStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slValoresStateChanged
        //c=(F-32)*1.8     f=C*1.8+32
        //------------------------------
        double c = (slValores.getValue() - 32) * 1.8;
        lbCentigrados.setText("" + String.format("%.2f", c));
        double f = (c * 1.8) + 32;
        lbFahrenheit.setText("" + String.format("%.2f", f));
        if (c >= -150 && c <= -10) {
            pnPrincipal.setBackground(Color.blue);
            lbNieve.setVisible(true);//Hace aparecer el label de nieve (solo en este rango se puede ver el label de nieve)
        } else {
            lbNieve.setVisible(false);//Oculta de nuevo el label de nieve
        }
        if (c >= -9 && c <= 5) {
            pnPrincipal.setBackground(Color.LIGHT_GRAY);
            lbFrio.setVisible(true);
        } else {
            lbFrio.setVisible(false);
        }
        if (c >= 6 && c <= 25) {
            pnPrincipal.setBackground(Color.YELLOW);
            lbTemplado.setVisible(true);
        } else {
            lbTemplado.setVisible(false);
        }
        if (c >= 26 && c <= 74) {
            pnPrincipal.setBackground(Color.ORANGE);
            lbCalido.setVisible(true);
        } else {
            lbCalido.setVisible(false);
        }
        if (c >= 75 && c <= 250) {
            pnPrincipal.setBackground(Color.RED);
            lbCaluroso.setVisible(true);
        } else {
            lbCaluroso.setVisible(false);
        }

    }//GEN-LAST:event_slValoresStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCalido;
    private javax.swing.JLabel lbCaluroso;
    private javax.swing.JLabel lbCentigrados;
    private javax.swing.JLabel lbFahrenheit;
    private javax.swing.JLabel lbFrio;
    private javax.swing.JLabel lbNieve;
    private javax.swing.JLabel lbTemplado;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbc;
    private javax.swing.JLabel lbf;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JSlider slValores;
    // End of variables declaration//GEN-END:variables
}
